### ISSUE TITLE
Feat: add alias support

### ISSUE THREAD

**Issue by major0** [major0/protondrive-cli#8]
Support for creating custom aliases/tags for VolumeID/ShareID references to be used in the UI as a substitute for the ID.

CLI interface:
`proton [vol|share] alias [add|del|rename|list] <option>`

Aliases for the `default` account could be added to the config as such:
```yaml
default:
  aliases:
    volume:
      id1: alias1
      id2: alias2
   share:
      id3: alias3
      id4: alias4
```
